sudo: required
services:
 - docker

before_install:
 - docker build -t dice/docker-react -f Dockerfile.dev .
 - docker build -t dice/docker-react-prod .

script:
 - docker run -e CI=true dice/docker-react npm run test
 - docker run -e CI=true dice/docker-react-prod

